#!/usr/bin/env bash
# Run the 22 formal jobs and write curated, auditable tails.
# Run from formal/run on the farm (vcf on PATH).
set -euo pipefail
cd "$(dirname "$0")"
# shellcheck source=evidence_counts.sh
source "$(dirname "$0")/evidence_counts.sh"
mkdir -p logs
raw_dir="$(mktemp -d)"

clean_jobs=(fpv_run_top fpv_run_seq fpv_run_lane_bf16 fpv_run_align_bf16 \
  fpv_run_round_bf16 fpv_run_special_bf16 fpv_run_bf16_top fpv_run_lane_nvfp4 \
  fpv_run_scale_nvfp4 fpv_run_round_nvfp4 fpv_run_nvfp4_top)
bug_jobs=(fpv_run_top_buginjected fpv_run_seq_buginjected \
  fpv_run_lane_bf16_buginjected fpv_run_lane_bf16_oor_buginjected \
  fpv_run_align_bf16_buginjected fpv_run_round_bf16_buginjected \
  fpv_run_bf16_top_buginjected fpv_run_lane_nvfp4_buginjected \
  fpv_run_scale_nvfp4_buginjected fpv_run_round_nvfp4_buginjected \
  fpv_run_nvfp4_top_buginjected)

capture_one() {
  local job="$1" kind="$2" raw="${raw_dir}/$1.raw" out="logs/$1.log"
  echo "RUN ${job} (${kind})"
  vcf -batch -f "${job}.tcl" >"$raw" 2>&1 || true   # falsified jobs return nonzero; verdict is derived from log

  # Deterministic tail: version banner + timestamp + model stats + assertion table.
  {
    grep -m1 -i 'version' "$raw" || echo "Tool version: (not printed)"
    grep -m1 -iE 'date|run' "$raw" || true
    grep -m1 -iE 'gate|input' "$raw" || true
    echo "----- assertion status -----"
    grep -iE 'proven|falsified|covered|unreachable' "$raw" | grep -viE 'EVIDENCE_VERDICT' || true
  } > "$out"

  # Machine-readable verdict: count only property rows (a_/p_/c_ names), not headers/summaries.
  local proven falsified covered
  read -r proven falsified covered < <(derive_verdict_counts "$raw")
  echo "EVIDENCE_VERDICT: job=${job} kind=${kind} proven=${proven} falsified=${falsified} covered=${covered}" >> "$out"
}

for j in "${clean_jobs[@]}"; do capture_one "$j" clean; done
for j in "${bug_jobs[@]}";  do capture_one "$j" bug;   done

# Roll-up summary from the verdict lines.
{
  echo "M5 formal regression roll-up  (generated by capture_evidence.sh)"
  grep -h '^EVIDENCE_VERDICT:' logs/*.log | sort
} > logs/RC_SUMMARY_m5.txt

echo "capture_evidence: wrote $(ls logs/*.log | wc -l) tails + RC_SUMMARY_m5.txt"
